name: Sync to Hugging Face hub
on:
  push:
    branches: [main] 
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Set up a temporary bot user
          git config --global user.email "bot@example.com"
          git config --global user.name "GitHub Action Bot"
          
          # 2. Delete the frontend folder from this temporary deployment
          git rm -rf frontend/ || true
          git commit -m "Exclude frontend and large video from Hugging Face" || true
          
          # 3. Force push only the backend code to Hugging Face
          git push --force https://MONKPIRATE:$HF_TOKEN@huggingface.co/spaces/MONKPIRATE/mei-arivu-api HEAD:main
