name: Sync to Hugging Face hub
on:
  push:
    branches: [main] 
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1 
          lfs: false
      - name: Push clean backend to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Destroy old git history
          rm -rf .git
          
          # 2. Move everything from 'backend' to the root directory
          mv backend/* . || true
          
          # 3. Delete folders we don't need for the API
          rm -rf frontend/
          rm -rf backend/
          
          # 4. Start fresh Git repo
          git init
          git checkout -b main
          git config user.email "bot@example.com"
          git config user.name "GitHub Action Bot"
          
          # 5. Track model files
          git lfs install
          git lfs track "*.pkl"
          git add .
          git commit -m "Deploy backend files to root"
          
          # 6. Force push
          git push --force https://MONKPIRATE:$HF_TOKEN@huggingface.co/spaces/MONKPIRATE/mei-arivu-api main
